[securityjourney]
title = "Security Journey Blog"
url = "https://www.securityjourney.com/resources/blog"
entrySelector = ".w-inline-block"
titleSelector = ".blog-card__title"
linkSelector = "*"
dateSelector = ".blog-card-date"
dateFormat = "MMMM d, y"
