[securityjourney]
title = "Security Journey Blog"
url = "https://www.securityjourney.com/resources/blog"
entrySelector = ".blog-horizontal-card__inner-wrap"
titleSelector = "a .w-inline-block > .blog-card__title"
linkSelector = "a .w-inline-block"
