[securityjourney]
title = "Security Journey Blog"
url = "https://www.securityjourney.com/resources/blog"
entrySelector = ".comp__blog-horizontal-card"
titleSelector = ".blog-card__title"
linkSelector = ".card-image-link-wrapper .w-inline-block"
