[securityjourney]
title = "Security Journey Blog"
url = "https://www.securityjourney.com/resources/blog"
entrySelector = ".blog-horizontal-card__inner-wrap"
titleSelector = ".blog-card__title"
linkSelector = "a"
dateSelector = ".blog-card-date"
dateFormat = "MMMM d, y"
