[securityjourney]
title = "Security Journey Blog"
url = "https://www.securityjourney.com/resources/blog"
entrySelector = ".comp__blog-horizontal-card"
titleSelector = ".blog-card__title"
linkSelector = ".w-inline-block"
dateSelector = ".blog-card-date"
dateFormat = "MMMM d, y"
